# Generated by Django 2.1.5 on 2019-12-16 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emailapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='receiver_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
